package ru.moondi.rallyinfo

const val URL_STREAM_KEY = "urlStream"
const val URL_RESULTS_KEY = "urlResults"
const val URL_SITE_NEWS_KEY = "urlSiteNews"
const val URL_RESULTS_DAKAR_KEY = "urlDakarResults"
const val URL_STREAM_VALUE = "https://wrc-info.ru/main/news/wrc/23545-video-transljacija-ralli-akropolis-grecija-2022-wrc.html"
const val URL_RESULTS_VALUE = "https://www.wrc.com/en/wrcplus/live-timing/"
const val URL_RESULTS_DAKAR_VALUE = "https://wrc-info.ru/online/dakar2023/results.php"
const val URL_SITE_NEWS_VALUE = "https://wrc-info.ru/index.php?action=mobile"
const val NAME_APP_PREFERENCE = "NAME_APP_PREFERENCES"
const val URL_KEY = "URL_KEY"
const val DEFAULT_URL_VALUE = ""
const val URL_VIDEO_WRC = "https://wrc-info.ru/main/video-wrc/"
const val URL_VIDEO_DAKAR = "https://wrc-info.ru/main/video-dakar/"
const val URL_NEWS_WRC = "https://wrc-info.ru/main/news/wrc/"
const val URL_NEWS_ERC = "https://wrc-info.ru/main/news/erc-rally/"
const val URL_NEWS_DAKAR = "https://wrc-info.ru/main/news/dakar/"
